services:
  chat-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq
    restart: unless-stopped
    environment:
      MONGODB_URI: "mongodb://root:W4d1v6tyYu@mongodb:27017/chat?authSource=admin"
      JWT_SECRET: "dev-secret-change-me"
      PORT: 8080
      RABBITMQ_URI: "amqp://guest:guest@rabbitmq:5672/"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: W4d1v6tyYu
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db:rw

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # RabbitMQ broker
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq:rw
